import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import React from 'react';
import Layout from "@/components/Layout";
// const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "InnoWeaver",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" rel="stylesheet" />
      </head>
      <body className="light">
        <Layout>{children}</Layout>
      </body>
    </html >
  );
}
