/**
 * 设计相关的表情符号映射
 */
export const designEmojis: Record<string, string> = {
  // 中文关键词
  '设计': '🎨',
  '界面': '📱',
  '体验': '✨',
  '交互': '🖱️',
  '可用性': '👆',
  '原型': '📐',
  '布局': '📏',
  '风格': '🎭',
  '美学': '🌈',
  
  // 英文关键词 - 设计领域
  'design': '🎨',
  'graphic': '🖌️',
  'visual': '👁️',
  'industrial': '🏭',
  'product': '📦',
  'fashion': '👗',
  'interior': '🏠',
  'architectural': '🏛️',
  'game': '🎮',
  'web': '🌐',
  'app': '📱',
  'mobile': '📲',
  'print': '🖨️',
  'type': '🔤',
  'illustration': '🖼️',
  'branding': '🏷️',
  'logo': '✒️',
  
  // 英文关键词 - UI/UX
  'interface': '📱',
  'UI': '🖼️',
  'UX': '🧠',
  'user interface': '📱',
  'user experience': '🧠',
  'user-centered': '👤',
  'interaction': '🖱️',
  'usability': '👆',
  'accessibility': '♿',
  'navigation': '🧭',
  'wireframe': '📝',
  'prototype': '📐',
  'mockup': '🎭',
  'layout': '📏',
  'responsive': '📲',
  'adaptive': '🔄',
  'mobile-first': '📱',
  
  // 英文关键词 - 设计元素与原则
  'element': '🧩',
  'component': '🧩',
  'color': '🎨',
  'palette': '🎨',
  'typography': '🔤',
  'grid': '📏',
  'composition': '📐',
  'balance': '⚖️',
  'harmony': '🎵',
  'contrast': '◼️◻️',
  'rhythm': '🎵',
  'proportion': '📏',
  'hierarchy': '🔢',
  'pattern': '🔄',
  'texture': '🧶',
  'space': '✨',
  'form': '🔷',
  'shape': '⭐',
  'line': '〰️',
  'symmetry': '↔️',
  'asymmetry': '↗️',
  
  // 英文关键词 - 设计过程
  'process': '🔄',
  'workflow': '📋',
  'iteration': '🔁',
  'sketch': '✏️',
  'ideation': '💭',
  'concept': '💡',
  'draft': '✏️',
  'revision': '🔄',
  'feedback': '💬',
  'critique': '🔍',
  'presentation': '📊',
  'style guide': '📖',
  'moodboard': '🖼️',
  'collaborative': '👥',
  'handoff': '🤝',
  
  // 英文关键词 - 设计美学
  'aesthetic': '🌈',
  'style': '🎭',
  'minimalist': '⬜',
  'modern': '🔷',
  'vintage': '📜',
  'retro': '📻',
  'futuristic': '🚀',
  'organic': '🌿',
  'geometric': '📐',
  'abstract': '🔶',
  'elegant': '✨',
  'playful': '🎪',
  'clean': '✨',
  'bold': '💪',
  'subtle': '🕊️',
  'decorative': '🎀',
  'material': '🧱',
  'flat': '📄',
  'skeuomorphic': '🔲',
  'creative': '🎨',
}; 