/**
 * 创新和创意相关的表情符号映射
 */
export const innovationEmojis: Record<string, string> = {
  // 中文关键词
  '创新': '💫',
  '创意': '💭',
  '灵感': '✨',
  '想法': '💡',
  '概念': '🧩',
  '思考': '🤔',
  '发明': '⚡',
  '突破': '🚀',
  '革新': '🔄',
  '前沿': '🔭',
  '未来': '🔮',
  '思维': '🧠',
  '构思': '💭',
  '新颖': '🌟',
  
  // 英文关键词 - 创新思维
  'innovation': '💫',
  'innovative': '💫',
  'innovate': '💫',
  'creative': '💭',
  'creativity': '💭',
  'ideation': '💡',
  'idea': '💡',
  'ideas': '💡',
  'brainstorm': '🧠',
  'brainstorming': '🧠',
  'thinking': '🤔',
  'thought': '💭',
  'imagination': '🌈',
  'imagine': '💭',
  'insight': '⚡',
  'lateral thinking': '↔️',
  'divergent thinking': '🔀',
  'convergent thinking': '🔃',
  'mind map': '🕸️',
  'conceptual': '🧩',
  'conceptualization': '🧩',
  
  // 英文关键词 - 创新过程
  'inspiration': '✨',
  'inspired': '✨',
  'concept': '🧩',
  'conceive': '🧠',
  'envision': '👁️',
  'prototype': '🔧',
  'prototyping': '🔧',
  'experiment': '🧪',
  'exploration': '🧭',
  'discover': '🔍',
  'discovery': '🔍',
  'iteration': '🔁',
  'evolve': '🧬',
  'evolution': '🧬',
  'pivot': '🔄',
  'feedback': '💬',
  
  // 英文关键词 - 创新特征
  'invention': '⚡',
  'invent': '⚡',
  'breakthrough': '🚀',
  'transformative': '🔄',
  'transform': '🔄',
  'disrupt': '💥',
  'disruptive': '💥',
  'disruption': '💥',
  'revolutionary': '🚀',
  'revolution': '🔄',
  'radical': '💥',
  'novel': '🌟',
  'novelty': '🌟',
  'cutting-edge': '🔭',
  'leading-edge': '🔭',
  'state-of-the-art': '✨',
  'advanced': '🔝',
  'futuristic': '🔮',
  'visionary': '👁️',
  'pioneering': '🚀',
  'frontier': '🔭',
  
  // 英文关键词 - 创新产出
  'solution': '🔑',
  'improvement': '📈',
  'enhance': '📈',
  'optimization': '⚙️',
  'reinvent': '🔄',
  'redesign': '🔄',
  'reframe': '🖼️',
  'rethink': '🔄',
  'reimagine': '💭',
  
  // 英文关键词 - 创新文化
  'entrepreneurship': '👔',
  'entrepreneur': '👔',
  'startup': '🚀',
  'venture': '🚀',
  'incubator': '🥚',
  'accelerator': '🏎️',
  'initiative': '🏁',
  'trailblazer': '🥾',
  'game-changer': '🎮',
  'risk-taking': '🎲',
  'forward': '➡️',
  'forward-thinking': '🔮',
  'originality': '🌱',
  'original': '💫',
  'unique': '🔹',
  'unconventional': '🔶',
  'new': '✨',
  'fresh': '🍃',
  'experimental': '🧪',
  'alternative': '↪️',
  'different': '↔️',
  'change': '🔄',
  'progress': '➡️',
  'paradigm shift': '🔄',
}; 