/**
 * 研究相关的表情符号映射
 */
export const researchEmojis: Record<string, string> = {
  // 中文关键词
  '研究': '🔍',
  '实验': '🧪',
  '数据': '📊',
  '分析': '📈',
  '科学': '🔬',
  '理论': '📚',
  '发现': '💡',
  '论文': '📑',
  '调查': '🔎',
  '探索': '🧭',
  '观察': '👁️',
  
  // 英文关键词 - 研究行为
  'research': '🔍',
  'study': '📚',
  'investigate': '🔎',
  'explore': '🧭',
  'examine': '🔍',
  'analyze': '📈',
  'assess': '📋',
  'evaluate': '📊',
  'review': '👓',
  'survey': '📝',
  'observation': '👁️',
  'inquiry': '🔍',
  
  // 英文关键词 - 研究方法与工具
  'experiment': '🧪',
  'method': '🛠️',
  'methodology': '📋',
  'framework': '📐',
  'approach': '🛣️',
  'paradigm': '🔄',
  'technique': '⚙️',
  'procedure': '📋',
  'protocol': '📜',
  'hypothesis': '💭',
  'theory': '📚',
  'measure': '📏',
  'metric': '📊',
  'interview': '🎤',
  'questionnaire': '📝',
  'laboratory': '🧪',
  'field': '🏞️',
  
  // 英文关键词 - 数据相关
  'data': '📊',
  'analysis': '📈',
  'statistics': '📊',
  'dataset': '💾',
  'sample': '🧩',
  'variable': '🔀',
  'correlation': '↔️',
  'factor': '⚖️',
  'parameter': '🔢',
  'measurement': '📐',
  'quantitative': '🔢',
  'qualitative': '🔤',
  'empirical': '📊',
  'evidence': '🧾',
  
  // 英文关键词 - 研究成果
  'finding': '💡',
  'findings': '💡',
  'result': '🎯',
  'discovery': '💡',
  'insight': '💫',
  'conclusion': '🏁',
  'implication': '➡️',
  'recommendation': '📌',
  'publication': '📰',
  'paper': '📑',
  'article': '📄',
  'journal': '📓',
  'proceedings': '📚',
  'dissertation': '📕',
  'thesis': '📘',
  
  // 英文关键词 - 研究领域
  'science': '🔬',
  'scientific': '🔬',
  'academic': '🎓',
  'scholarly': '🧠',
  'interdisciplinary': '🔄',
  'psychology': '🧠',
  'sociology': '👥',
  'anthropology': '🌍',
  'biology': '🧬',
  'physics': '⚛️',
  'chemistry': '⚗️',
  'medicine': '💊',
  'economics': '💹',
  'humanities': '📜',
  'linguistics': '🔤',
  'cognitive': '🧠',
  'behavioral': '🔄',
  'clinical': '👨‍⚕️',
}; 