/**
 * 技术相关的表情符号映射
 */
export const techEmojis: Record<string, string> = {
  // 中文关键词
  '技术': '⚙️',
  '开发': '💻',
  '编程': '👨‍💻',
  '代码': '📝',
  '工程': '🔧',
  '应用': '📲',
  '系统': '🖥️',
  '网络': '🌐',
  '软件': '📀',
  '硬件': '🔌',
  '算法': '🧮',
  '人工智能': '🤖',
  '机器学习': '🧠',
  '数据库': '🗄️',
  '云': '☁️',
  
  // 英文关键词 - 技术通用
  'technology': '⚙️',
  'technical': '🔧',
  'engineering': '🔧',
  'innovation': '💡',
  'solution': '🔑',
  'system': '🖥️',
  'infrastructure': '🏗️',
  'architecture': '🏛️',
  'platform': '🏗️',
  'ecosystem': '🌐',
  'digital': '📱',
  'electronic': '💾',
  'automation': '🤖',
  
  // 英文关键词 - 软件开发
  'development': '💻',
  'programming': '👨‍💻',
  'code': '📝',
  'coding': '⌨️',
  'software': '📀',
  'application': '📲',
  'app': '📱',
  'developer': '👨‍💻',
  'engineer': '👷',
  'programmer': '👨‍💻',
  'debugging': '🐛',
  'testing': '🧪',
  'deployment': '🚀',
  'release': '🚀',
  'version': '🔢',
  'package': '📦',
  'module': '🧩',
  'library': '📚',
  'framework': '🧰',
  'repository': '📂',
  'commit': '✅',
  'merge': '🔀',
  'branch': '🌿',
  'agile': '🏃',
  'scrum': '🔄',
  'sprint': '🏃',
  
  // 英文关键词 - 编程语言与技术
  'javascript': '📜',
  'python': '🐍',
  'java': '☕',
  'html': '🌐',
  'css': '🎨',
  'react': '⚛️',
  'angular': '🅰️',
  'vue': '🟢',
  'node': '📦',
  'typescript': '📘',
  'php': '🐘',
  'ruby': '💎',
  'swift': '🦅',
  'kotlin': '🧩',
  'go': '🐹',
  'rust': '🦀',
  'c': '🎯',
  'c++': '🧮',
  'c#': '🎵',
  'sql': '🗃️',
  'nosql': '📊',
  'frontend': '🖥️',
  'backend': '⚙️',
  'fullstack': '🥞',
  'devops': '♾️',
  'git': '🔀',
  
  // 英文关键词 - 硬件与基础设施
  'hardware': '🔌',
  'device': '📱',
  'computer': '💻',
  'server': '🖧',
  'network': '🌐',
  'router': '📡',
  'chip': '💿',
  'processor': '💽',
  'memory': '🧠',
  'storage': '💾',
  'database': '🗄️',
  'cloud': '☁️',
  'azure': '☁️',
  'aws': '☁️',
  'google cloud': '☁️',
  'hosting': '🏢',
  'virtualization': '🖥️',
  'container': '📦',
  'docker': '🐳',
  'kubernetes': '⚓',
  
  // 英文关键词 - AI与数据科学
  'AI': '🤖',
  'artificial intelligence': '🤖',
  'machine learning': '🧠',
  'ML': '🧠',
  'deep learning': '🧠',
  'neural network': '🧠',
  'data science': '📊',
  'big data': '📊',
  'dataset': '💾',
  'algorithm': '🧮',
  'model': '🧩',
  'training': '🏋️',
  'test': '🧪',
  'prediction': '🔮',
  'classification': '📋',
  'clustering': '🔣',
  'regression': '📈',
  'tensorflow': '🧠',
  'pytorch': '🔥',
  'nlp': '🗣️',
  'computer vision': '👁️',
  'robotics': '🤖',
  
  // 英文关键词 - 网络与安全
  'web': '🌐',
  'internet': '🌐',
  'protocol': '📜',
  'mobile': '📱',
  'responsive': '📲',
  'security': '🔒',
  'crypto': '🔐',
  'blockchain': '⛓️',
  'encryption': '🔐',
  'firewall': '🛡️',
  'privacy': '🕶️',
  'authentication': '🔑',
  'authorization': '🔓',
  'identity': '👤',
  'credential': '🔑',
  'password': '🔒',
  'token': '🪙',
  'oauth': '🔄',
}; 